services:
  vtctf:
    image: repulsivityy/vt-ctf:version1
    ports:
      - 8000:8000
    profiles: ["vt"]
  domctf:
    image: repulsivityy/gti-ctf:version2
    ports:
      - 8000:8000
    profiles: ["domgti"]
  tarahctf:
    image: tklew/gti:latest
    ports:
      - 8000:8000
    profiles: ["tarah"]
  gus:
    image: tklew/gus:latest
    ports:
      - 8000:8000
    profiles: ["gus"]
    